import { Bath, Blocks, CookingPot, Grid3X3, Hammer, Sparkles } from "lucide-react";

export const servicePricing = [
  {
    id: "countertops",
    service: "Countertop project",
    shortName: "Countertops",
    startingAt: "$2,800",
    range: "$55–$140 / sq. ft. installed",
    description: "Template, fabrication, standard edge, installation, and one standard sink cutout.",
    icon: Sparkles,
    imageKey: "countertop",
    popular: true,
  },
  {
    id: "kitchen",
    service: "Kitchen remodeling",
    shortName: "Kitchen remodel",
    startingAt: "$18,000",
    range: "Typical range $25k–$75k+",
    description: "Design guidance, demolition, cabinets, surfaces, trade coordination, and installation.",
    icon: CookingPot,
    imageKey: "kitchen",
    popular: false,
  },
  {
    id: "bathroom",
    service: "Bathroom remodeling",
    shortName: "Bathroom remodel",
    startingAt: "$12,500",
    range: "Typical range $18k–$45k+",
    description: "Demolition, waterproofing, tile, shower or tub, vanity, fixtures, and coordination.",
    icon: Bath,
    imageKey: "bathroom",
    popular: false,
  },
  {
    id: "cabinets",
    service: "Cabinets",
    shortName: "Cabinets",
    startingAt: "$6,500",
    range: "$350–$1,200 / linear ft.",
    description: "Layout support, cabinet ordering, delivery coordination, hardware, and installation.",
    icon: Blocks,
    imageKey: "kitchen",
    popular: false,
  },
  {
    id: "backsplash",
    service: "Backsplash",
    shortName: "Backsplash",
    startingAt: "$1,200",
    range: "$25–$65 / sq. ft. installed",
    description: "Surface preparation, tile layout, installation, grout, sealant, and job-site cleanup.",
    icon: Grid3X3,
    imageKey: "backsplash",
    popular: false,
  },
  {
    id: "vanity",
    service: "Vanity",
    shortName: "Vanity & top",
    startingAt: "$1,850",
    range: "Typical range $2k–$7.5k",
    description: "Vanity cabinet, stone top, sink cutout, faucet drilling, delivery, and installation.",
    icon: Hammer,
    imageKey: "bathroom",
    popular: false,
  },
];

export const priceFactors = [
  "Material, color group, slab availability, and finish",
  "Square footage, room access, and layout complexity",
  "Edge profiles, seams, waterfall panels, and overhangs",
  "Sink, cooktop, faucet, outlet, and specialty cutouts",
  "Cabinet condition, wall preparation, demolition, and disposal",
  "Plumbing, electrical, flooring, permit, and coordination requirements",
];
